### ISSUE TITLE
pride remove <module> command fails to delete all files on MS Windows

### ISSUE THREAD

**Issue by coenwouters** [prezi/pride#134]
On Windows the pride remove <module> command fails with:
IOException: Cannot delete file <some file>

The problem does not seem to be related to a specific file and/or version of Windows. The file is not locked and can be removed by using the Windows Explorer.

**Comment by lptr** [comment]
Can you provide a full log with `pride remove -v <module>` please?

**Comment by coenwouters** [comment]
I cannot reproduce the problem anymore using Pride 0.10

**Comment by coenwouters** [comment]
The problem just occured again, but it is not clear yet how to reproduce it. 

I did get the following output:
[1/1] Removing nl.planon.ee.facilityoffice
Removing nl.planon.ee.facilityoffice from C:\Gradle\ws\nl.planon.ee.facilityoffice
ERROR: Exception:
java.io.IOException: Unable to delete directory C:\Gradle\ws\nl.planon.ee.facilityoffice\src\main\java\nl\planon\aphrodite\businessmodel\caddrawingdefinition\parts\linkedbo\parts\bomapping.
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
        at com.prezi.pride.Pride.removeModule(Pride.java:168) ~[pride-core-0.10.jar:na]
        at com.prezi.pride.cli.commands.RemoveCommand$2.execute(RemoveCommand.java:58) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.RemoveCommand$2.execute(RemoveCommand.java:55) ~[pride-0.10.jar:na]
        at com.prezi.pride.internal.LoggedProgressAction.execute(LoggedProgressAction.java:31) ~[pride-core-0.10.jar:na]
        at com.prezi.pride.internal.ProgressUtils.execute(ProgressUtils.java:12) ~[pride-core-0.10.jar:na]
        at com.prezi.pride.cli.commands.RemoveCommand.executeInModules(RemoveCommand.java:55) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.AbstractFilteredPrideCommand.executeInPride(AbstractFilteredPrideCommand.java:87) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.AbstractPrideCommand.executeWithConfiguration(AbstractPrideCommand.java:10) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.AbstractConfiguredCommand.call(AbstractConfiguredCommand.java:30) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.AbstractConfiguredCommand.call(AbstractConfiguredCommand.java:11) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.PrideCli.execute(PrideCli.java:84) [pride-0.10.jar:na]
        at com.prezi.pride.cli.PrideCli.main(PrideCli.java:27) [pride-0.10.jar:na]

**Comment by lptr** [comment]
One idea: isn't your IDE or a virus scanner holding onto that directory?

**Comment by coenwouters** [comment]
I do not have an IDE open. My virus scanner is configured to ignore java source and target files. I will check my installation whether there could be other tools that monitor disk activity
