### ISSUE TITLE
Pride error when including project with subprojects on Windows

### ISSUE THREAD

**Issue by coenwouters** [prezi/pride#139]
We have a standalone project which is a multi project build on its own. When we include this in our pride workspace, then pride fails to initialize the pride workspace settings.gradle. This is caused by the fact that it cannot calculate the relative URI of the subproject based on the windows paths. The File API should be used to translate the path to a proper URI.

Project structure:
nl.planon.assembly
                sdk
                suite

nl.planon.assembly/settings.gradle (include 'sdk', 'suite')

ERROR: Exception:
com.prezi.pride.PrideException: There was a problem during the initialization of the pride. Fix the errors above, and try again with pride init --force
        at com.prezi.pride.cli.PrideInitializer.reinitialize(PrideInitializer.java:118) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.actions.InitAction.initPride(InitAction.java:94) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.actions.InitActionBase.createPride(InitActionBase.java:53) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.InitCommand.executeWithConfiguration(InitCommand.java:86) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.AbstractConfiguredCommand.call(AbstractConfiguredCommand.java:30) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.commands.AbstractConfiguredCommand.call(AbstractConfiguredCommand.java:11) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.PrideCli.execute(PrideCli.java:84) [pride-0.10.jar:na]
        at com.prezi.pride.cli.PrideCli.main(PrideCli.java:27) [pride-0.10.jar:na]
Caused by: java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: F:\HEAD\workspace
        at java.net.URI.create(URI.java:852) ~[na:1.8.0_31]
        at com.prezi.pride.cli.PrideInitializer.writeSettingsForChildren(PrideInitializer.java:143) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.PrideInitializer.createSettingsFile(PrideInitializer.java:136) ~[pride-0.10.jar:na]
        at com.prezi.pride.cli.PrideInitializer.reinitialize(PrideInitializer.java:115) ~[pride-0.10.jar:na]
        ... 7 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: F:\HEAD\workspace
        at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_31]
        at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_31]
        at java.net.URI$Parser.parse(URI.java:3058) ~[na:1.8.0_31]
        at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_31]
        at java.net.URI.create(URI.java:850) ~[na:1.8.0_31]
        ... 10 common frames omitted

**Comment by lptr** [comment]
Can you please test if this pull-request fixes the problem?
https://github.com/prezi/pride/pull/142

**Comment by coenwouters** [comment]
We have verified that the changes indeed solve this issue. It also solves a problem with specifying the config file on the init command.
Thank you for your assistance.
